# Generated by Django 3.2.2 on 2021-05-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('home', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=20)),
                ('studentnum', models.IntegerField()),
                ('lover', models.BooleanField()),
                ('food', models.CharField(max_length=20)),
                ('alcohol', models.CharField(max_length=20)),
                ('dream', models.TextField()),
            ],
        ),
    ]
