# Generated by Django 3.2.2 on 2021-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='lover',
            field=models.CharField(max_length=10),
        ),
    ]
